spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_db
    username: test
  h2:
    console:
      enabled: true
      path: /h2/console
  mvc:
    servlet:
      path: /root